### ISSUE TITLE
[Insight] Text files should end with a newline character - in readme.md, line 26

### ISSUE THREAD

**Issue by Tjoosten** [Scouts-Sint-Joris/SIJOT-2.x#2]
**[in readme.md, line 26](https://github.com/Scouts-Sint-Joris/SIJOT-2.x/blob/c05ee31395ec911f319ce0a721436a0653e80a87/readme.md#L26)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```
## License

The Sijot website is open-sourced software licensed under the [MIT license](http://opensource.org/licenses/MIT).

## Contributing
Contributions are highly appreciated. Please read the [contribution guidelines](contributing.md) here.
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/22e7c844-d621-46e2-a627-35aa33008a17/analyses/3)_

**Comment by varanauskas** [comment]
I'm on this
